name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Setup Gluon
        run: pnpm i

      - name: Check license
        run: pnpm run gluon lc

  build-test:
    name: Build test
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Setup Gluon
        run: pnpm i

      - name: Check license
        run: pnpm run gluon lc

      - name: Load gluon CI setup
        run: pnpm gluon ci --brand test --display-version 0.0.0

      - name: Download firefox source and dependancies
        run: pnpm download --verbose

      - name: Extension check
        run: |
          EXTS=($(cat gluon.json | jq -r ".addons | keys[]"))

          for i in "${EXTS[@]}"; do
              find ./engine/browser/extensions/$i -maxdepth 0 -empty
              #[ "$(find ./engine/browser/extensions/$i -maxdepth 0 -empty)" ] && exit 1
          done

      - name: Import (Patch test)
        run: pnpm imp --verbose
